### ISSUE TITLE
Неоправданное использование оператора объединения из php7

### ISSUE THREAD

**Issue by acidka** [andkon13/yii2-klard#2]
Используя оперетор объединения из php7 вот тут 
[https://github.com/andkon13/yii2-klard/blob/master/Kladr.php#L102 ](https://github.com/andkon13/yii2-klard/blob/master/Kladr.php#L102 )
вы слелали свой виджет php7 only... На версии 5.7 к примеру тупо падает...

**Comment by andkon13** [comment]
Действительно просочился код с 7-ки. понизил версию.
