### ISSUE TITLE
Дефолтные данные в поле модели

### ISSUE THREAD

**Issue by yanmandev** [andkon13/yii2-klard#4]
Виджет ставился в рабочий проект, где в полях модели, например city, пользователями были указаны "текст рыба" или города с ошибкой. При этом появляется warning error http://prntscr.com/e26gzl:
`PHP Warning – yii\base\ErrorException`
`file_get_contents(http://kladr-api.ru/api.php?contentType=city&amp;cityId=пцпцуп&amp;token=5538caef7c52390a328b45c7): failed to open stream: HTTP request failed! HTTP/1.1 400 cityId incorrect`

**Comment by andkon13** [comment]
При переходе из одной системы в другую, мне кажется надо подготовить модель в которой сдержатся данные об адресах. Если допустим у вас в поле city было бы не "текст рыба", а id города, но из другой системы (не кладр) то вы бы получили пусть не Exception, но неверный город, так как в кладре этот id принадлежит другому городу или вообще отсутствует.
Дефолтные значения в данном случаи дадут непредсказуемый результат и при внезапном переходе с кладра на какой либо еще сервис (product owner может быть таким внезапным) будет еще сложнее определить у вас в поле city старые данные, данные из кладка или что то дефлтное.
Добавьте kladr_city_id (как минимум на переходный период) и работайте с ним.
Это даст возможность откатится, и контролировать правильно ли у вас соотносятся старые значения с идентификаторами в кладр.
