### ISSUE TITLE
Поиск улиц с заданым городом

### ISSUE THREAD

**Issue by RevProg** [andkon13/yii2-klard#5]
Не могу понять как искать по улицы, задав город в параметрах виджета. Есть ли такая возможность? Спасибо

**Comment by andkon13** [comment]
Для задания улицы надо сделать отдельное поле с типом STREET, для выбора дома BUILDING и тд. 
Форма будет примерно такая https://kladr-api.ru/examples#form

**Comment by RevProg** [comment]
Вопрос был как сделать поиск по улицами не имея поле с типом CITY? Id города могу вбить в настройки виджета например.

**Comment by acidka** [comment]
Добавить невидимое поле city и прописать ему сразу нужное значение, например "7800000000000" для "г.Санкт-Петербург"
