### ISSUE TITLE
Неверный путь к Bower-asset

### ISSUE THREAD

**Issue by kirc0de** [andkon13/yii2-klard#6]
Если bower ассеты установлены в папку bower-asset, то юи будет ругаться из-за неправильного пути в ассете.

**Comment by robotE13** [comment]
Да, действительно алиас пути неверный, поскольку в поздних версиях Yii отказались от fxp-asset-plugin. Теперь папка для bower называется bower-asset

Чтобы исправить данную ошибку в проекте не надо клоны репозиториев делать и т п вещи. Достаточно использовать контейнер внедрения зависимостей:

`
Yii::$container->set(andkon\yii2kladr\assets\KladrAsset::className(), 'sourcePath'=>'@bower/jquery.kladr']);`
