### ISSUE TITLE
При использовании кода из примера возникают ошибки

### ISSUE THREAD

**Issue by Dkalugin** [andkon13/yii2-klard#9]
После установки и вставки во view кода из примера возникают ошибки:
1. сразу выдает `Invalid Argument – yii\base\InvalidArgumentException`
Ругается, что не найден `/vendor/bower/jquery.kladr`
Проверил, нет в `vendor `каталога `bover`. Создал руками, скопировал туда jquery.kladr

2. выдает `PHP Notice – yii\base\ErrorException`
`Undefined index: building`
ругается на `/vendor/andkon/yii2kladr/Kladr.php`
на строку 134
`$zipJs = '$("#' . self::$inputs[self::TYPE_BUILDING][1] . '")`

**Comment by createsite2016** [comment]
в файле:
/vendor/andkon/yii2kladr/assets/KladrAsset.php 

поменяйте значение с: 
public $sourcePath = '@vendor/bower/jquery.kladr';

на это значение:
public $sourcePath = '@vendor/bower-asset/jquery.kladr';

**Comment by Dkalugin** [comment]
Спасибо, уже не актуально.
